# Generated by Django 2.2.5 on 2019-09-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.IntegerField()),
                ('codigo_orcamento', models.IntegerField()),
                ('codigo_produto', models.IntegerField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('data', models.DateField(auto_now=True)),
                ('status', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
